---
# tasks file for setup_openshift4

  - name: Copy a ocp4 directory for backup
    copy: 
      src: /opt/ocp4
      dest: /opt/ocp4_{{ansible_date_time.iso8601_micro}}
      remote_src: yes
  # - import_tasks: ../handlers/main.yml

  - name: import var files 
    include_vars: "{{ item }}"
    with_items:
      - "{{ role_path }}/../../artifacts/host_inventory.yml"

  - name: slurp the pubkey for passing to other servers as authorized_key
    slurp:
      src: /opt/ocp4/ocp4_rsa.pub
    register: new_rsa_key
 


  # - name: import var files 
  #   include_vars: "{{ item }}"
  #   with_items:
  #     - "{{ role_path }}/../update-helpernode/vars/main.yml"

  # According to RFC 952, and RFC 1123, also RFC about SRV records should be taken into account)
  # underscores in hostnames are illegal.

  # - name: validate hostnames
  #   import_tasks: validate_host_names.yaml

  - name: Read the .crt file content
    slurp:
      src: /opt/registry/certs/domain.crt
    register: slurp_remote_file

  - name: Cert Content
    set_fact: cert={{ slurp_remote_file['content'] | b64decode }} 

  - name: Cert Content
    set_fact: cert_json={{ cert| to_nice_json(indent=2) }}


  


  - name: Set Facts for password and user base64encoded
    set_fact: HTTP_AUTH="{{'dummy:dummy' | b64encode }}"


  - name: Write out install-config file
    template:
      src: "{{ role_path }}/templates/install-config.yaml.j2"
      dest: /opt/ocp4/install-config.yaml




  - name: copy install-config.yaml file for forensic
    copy:
      src: /opt/ocp4/install-config.yaml
      dest: /opt/ocp4/install-config.yaml.bak_noVyatta
      remote_src: yes
       

  - name: Run openshift-install command
    command: chdir=/opt/ocp4 openshift-install create ignition-configs --dir=/opt/ocp4


  - name: copy the ignition files to http server location
    copy:
      src: /opt/ocp4/{{item}} 
      dest: /var/www/html/ignition/
      mode: '0644'
      remote_src: yes
    with_items: 
     ['master.ign', 'bootstrap.ign', 'worker.ign']

  - name: restocon command on http server
    command: restorecon -vR /var/www/html/
