---
- block:
  - set_fact:
      packages:
        - podman
        - httpd-tools
        - pyOpenSSL
        - net-tools
        - python3
        - git
        - epel-release
        - podman
        - httpd-tools
        - gcc 
        - libffi-devel 
        - python-devel
        - openssl-devel
        - bash-completion
        - python3-libselinux
        - nfs-utils
        - net-tools
        - libfaketime
        - docker

  
  - set_fact:
      dhcppkgs:
        - dhcp
        - syslinux
        - tftp-server
  
  - set_fact:
      owner: nfsnobody
      group: nfsnobody
  
  - set_fact:
      services:
        - named
        - haproxy
        - httpd
        - rpcbind
        - nfs-server
        - nfs-lock
        - nfs-idmap
        - docker

  when: ansible_distribution_major_version == "7"

- block:
  - set_fact:
      epel-packages:
        - epel-release
        

  
  - set_fact:
      dhcppkgs:
        - dhcp-server
        - syslinux
        - tftp-server
  
  # See Fedora Wiki for changes:
  # https://fedoraproject.org/wiki/Changes/RenameNobodyUser
  - set_fact:
      owner: nobody
      group: nobody
  
  - set_fact:
      services:
        - named
        - haproxy
        - httpd
        - rpcbind
        - nfs-server
  when: ansible_distribution_major_version == "8"
