---
ssh_gen_key: true
install_filetranspiler: false
staticips: false
force_ocp_download: false
ocp_bios: "{{ v_rhcos_bios }}"
ocp_initramfs: "{{ v_rhcos_initramfs }}"
ocp_install_kernel: "{{ v_rhcos_install_kernel }}"
ocp_client: "{{ v_ocp_client }}"
ocp_installer: "{{ v_ocp_installer }}"
disk: xvda
default_nic: "eth0"

sshd_config: "/etc/ssh/sshd_config"

helper:
  name: "{{ ansible_hostname }}"
  ipaddr: "{{ ansible_default_ipv4.address }}"
  networkifacename: "{{ ansible_default_ipv4.interface }}"



