- name: Get the SSL ssh keyid
  register: contentof_sl_sshkeys
  shell: "slcli sshkey list | grep ocp-key | awk '{print $1;}'"

- name: Fact IBM Cloud ssh key 
  set_fact:
    sl_ssh_key: "{{ contentof_sl_sshkeys.stdout_lines | list }}"
 
  

  #   B1_8X16X100

#################
# helper
##################
- name: Create Helpernode VSI IBM Cloud
  expect:
    command: "slcli vs create --hostname={{ item }} --domain={{ base_domain_prefix }}.{{ base_domain }} -f B1_4X8X100 -o CENTOS_LATEST_64  --datacenter={{ sl_datacenter }} --billing={{ sl_vsi_billing }}  -k ocp-key  --private --vlan-private={{ sl_vlan_id }} --network {{ network_speed }}"
    responses: 
      (?i)Continue?: "y"
  register: contentof_helpernode_info
  with_items: "{{ sl_ocp_helpernode }}"
  loop_control:
        pause: 15 
  when: sl_vyatta|bool == true
  
- name: Create Helpernode VSI on IBM Cloud
  expect:
    command: "slcli vs create --hostname={{ item }} --domain={{ base_domain_prefix }}.{{ base_domain }} -f B1_4X8X100 -o CENTOS_LATEST_64  --datacenter={{ sl_datacenter }} --billing={{ sl_vsi_billing }}  -k ocp-key   --vlan-private={{ sl_vlan_id }} --network {{ network_speed }}"
    responses: 
      (?i)Continue?: "y"
  register: contentof_helpernode_info
  with_items: "{{ sl_ocp_helpernode }}"
  loop_control:
        pause: 15 
  when: sl_vyatta|bool == false


#################
# bootstrap
##################

- name: Create Bootstrap node VSI on IBM Cloud
  expect:
    command: "slcli vs create --hostname={{ item }} --domain={{ base_domain_prefix }}.{{ base_domain }} -f B1_4X8X100 -o CENTOS_LATEST_64  --datacenter={{ sl_datacenter }} --billing={{ sl_vsi_billing }}  -k ocp-key  --private --vlan-private={{ sl_vlan_id }} --network {{ network_speed }}"
    responses: 
      (?i)Continue?: "y"
  register: contentof_bootstrap_info
  with_items: "{{ sl_ocp_bootstrap }}"
  loop_control:
        pause: 15 









#################
# Masters
##################





- name: Create Master Nodes VSI on IBM Cloud
  expect:
    command: "slcli vs create --hostname={{ item }} --domain={{ base_domain_prefix }}.{{ base_domain }} -f B1_8X16X100 -o CENTOS_LATEST_64  --datacenter={{ sl_datacenter }} --billing={{ sl_vsi_billing }}  -k ocp-key  --private --vlan-private={{ sl_vlan_id }} --network {{ network_speed }}"
    responses: 
      (?i)Continue?: "y"
  register: contentof_master0_info
  with_items: "{{ sl_ocp_masters }}"
  loop_control:
        pause: 15 








- name: Create Worker Nodes VSI on IBM Cloud
  expect:
    command: "slcli vs create --hostname={{ item }} --domain={{ base_domain_prefix }}.{{ base_domain }} -f B1_8X16X100 -o CENTOS_LATEST_64  --datacenter={{ sl_datacenter }} --billing={{ sl_vsi_billing }}  -k ocp-key  --private --vlan-private={{ sl_vlan_id }} --network {{ network_speed }}"
    responses: 
      (?i)Continue?: "y"
  register: contentof_worker0_info
  with_items: "{{ sl_ocp_workers }}"
  loop_control:
        pause: 15 




# A helpful reminder of what to look out for post-update.
- pause:
    minutes: "{{vsi_provison_pause}}"