
###############################################
# Get info for all the bootstrap nodes 
###############################################

 - name: Get Bootstrap hostinfo
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_bootstrapnodes
   with_items: " {{ sl_ocp_bootstrap }}"



 - name: registering the entire list to new variable Bootstrap
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_bootstrapnodes.results }}"
   register: contentof_bootstrapnodes_stdout

 - name: Add IP infomration to helper hosts variable
   set_fact:
     allbootstrapnodehostsinfo: "{{ allbootstrapnodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allbootstraphostids: "{{ allbootstraphostids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_bootstrapnodes_stdout.results }}"
   no_log: True



###############################################
# Get info for all the helper nodes 
###############################################

 - name: Get Helpernode hostinfo
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_helpernodes
   with_items: " {{ sl_ocp_helpernode }}"

 - name: registering the entire list to new variable helper
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_helpernodes.results }}"
   register: contentof_helpernodes_stdout

 - name: Add IP infomration to helper hosts variable
   set_fact:
     allhelpernodehostsinfo: "{{ allhelpernodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allhelpernodehostids: "{{ allbootstrapallhostids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_helpernodes_stdout.results }}"







###############################################
# Get info for all the master nodes 
###############################################


 - name: Get Masternodes hostinfo
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_mastersnodes
   with_items: " {{ sl_ocp_masters }}"


 - name: Registering the entire list to new variable master
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_mastersnodes.results }}"
   register: contentof_mastersnodes_stdout

 - name: Add IP infomration to master hosts variable
   set_fact:
     allmasternodehostsinfo: "{{ allmasternodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allmasternodehostsids: "{{ allmasternodehostsids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_mastersnodes_stdout.results }}"






##############################################
# Get info for all the worker nodes 
###############################################

 - name: Get Workernodes hostinfo
   expect:
     command: "slcli --format json  vs detail {{ item }}"
     responses: 
       (?i)Continue?: "y"
   register: contentof_workernodes
   with_items: " {{ sl_ocp_workers }}"




 - name: Registering the entire list to new variable
   set_fact: 
     dataresult: "{{ item.stdout | from_json }}"
   with_items:
       - "{{ contentof_workernodes.results }}"
   register: contentof_workernodes_stdout
 


 - name: Add IP information to hosts variable
   set_fact:
     allworkernodehostsinfo: "{{ allworkernodehostsinfo|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.private_ip} ) }}"
     allworkernodehostsids: "{{ allworkernodehostsids|default({}) | combine( {item.ansible_facts.dataresult.hostname: item.ansible_facts.dataresult.id} ) }}"
   with_items:
       - "{{ contentof_workernodes_stdout.results }}"
 

# Print out all the host info

 - name: debug
   debug:
     var: allworkernodehostsinfo
   when: debug|default(false) == true
 - name: debug
   debug:
     var: allhelpernodehostsinfo
   when: debug|default(false) == true
 - name: debug
   debug:
     var: allbootstrapnodehostsinfo
   when: debug|default(false) == true
 - name: debug
   debug:
     var: allmasternodehostsinfo
   when: debug|default(false) == true



### write out the host file 
#  - name: Write out host into to a file
#    template:
#      src: "{{ role_path }}/templates/allhostinfo.j2"
#      dest: "{{ role_path }}/../../hosts"

 - name: Write out host into to a  artifacts folder
   template:
     src: "{{ role_path }}/templates/allhostinfo.j2"
     dest: "{{ role_path }}/../../artifacts/hosts"

 - name: Remove files
   file:
     path: "{{ role_path }}/../restart_ic4g_ocp_servers/vars/main.yml"
     state: absent
 
 - name: Write out host into to a file
   template:
     src: "{{ role_path }}/templates/allhostic4gids.j2"
     dest: "{{ role_path }}/../restart_ic4g_ocp_servers/vars/main.yml"

 - name: Write out host into to a artifacts folder
   template:
     src: "{{ role_path }}/templates/allhostic4gids.j2"
     dest: "{{ role_path }}/../../artifacts/main.yml"

#  - name: Shutdown Pubic Port for Helper node
#    expect:
#      command: "slcli vs edit {{ item }} --public-speed 0"
#      responses: 
#        (?i)Continue?: "y"
#    with_items: " {{ sl_ocp_helpernode }}"
#    when: sl_vyatta|bool == false
     
            