---
# tasks file for pre_new_vsi_machine

- name: Ensure SELinux is set to enforcing mode
  lineinfile:
    path:  /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: GRUB_TIMEOUT=2

- name: Copy 40_custom gurb  file
  copy:
    src: "{{ role_path }}/files/40_custom"
    dest: /etc/grub.d/40_custom


- name: execute command on remote system.
  command:  grub2-mkconfig -o /boot/grub2/grub.cfg
  
- name:  execute command on remote system
  command: grub2-set-default 3




