---
# tasks file for create_opc_host_inventory


### write out the host file 
 - name: Write out host information to a file
   template:
     src: "{{ role_path }}/templates/host_inventory.j2"
     dest: "{{ role_path }}/../../artifacts/host_inventory.yml"
   delegate_to: localhost
